name: Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build as a tar.gz
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Get latest package from gcs-back-end
        run: curl -L https://github.com/CMIPT/gcs-back-end/releases/latest/download/gcs-back-end.tar.gz -o gcs-back-end.tar.gz

      - name: Append .output to gcs-back-end
        run: |
          gunzip gcs-back-end.tar.gz
          tar --append -f gcs-back-end.tar .output
          gzip gcs-back-end.tar
          mv gcs-back-end.tar.gz gcs.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcs
          path: gcs.tar.gz

  release:
    name: Release to GitHub
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: gcs

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
          files: gcs.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
